models/node.py
from . import ModelMixin
from . import db
from . import timestamp


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    created_time = db.Column(db.Text, default=0)
    topics = db.relationship('Topic', backref="node")

    def __init__(self, form):
        self.name = form.get('name', '')
        self.created_time = timestamp()

models/topic.py
from . import ModelMixin
from . import db
from . import timestamp


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    content = db.Column(db.Text)
    created_time = db.Column(db.Text, default=0)
    comments = db.relationship('Comment', backref="node")
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.node_id = form.get('node_id', '')
        self.user_id = form.get('user_id', '')
        self.created_time = timestamp()
        self.comments_num = 0
        self.last_comment_user = ''
        self.last_comment = ''


    def comments_num(self):
        self.comments_num = len(self.comments)
        if self.comments_num == 0:
            return None
        return self.comments_num

    def last_comment_user(self):
        if len(self.comments) == 0:
            return None
        return self.comments[-1].user

    def last_comment(self):
        if len(self.comments) == 0:
            return None
        return self.comments[-1]

routes/comment.py
from models.comment import Comment
from routes import *


main = Blueprint('comment', __name__)

Model = Comment


@main.route('/')
def index():
    ms = Model.query.all()
    return render_template('comment_index.html', comment_list=ms)


@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    if u is not None:
        form = request.form
        m = Model(form)
        m.save()
        topic_id = m.topic_id
        return redirect(url_for('topic.show', id=topic_id, u=u))
    return render_template('register_or_login.html')

# @main.route('/<int:id>')
# def show(id):
#     m = Model.query.get(id)
#     return render_template('topic.html', topic=m)


@main.route('/delete/<int:id>')
def delete(id):
    m = Model.query.get(id)
    m.delete()
    return redirect(url_for('.index'))

routes/home.py
from models.node import Node
from models.topic import Topic
from routes import *


main = Blueprint('home', __name__)


@main.route('/')
def home():
    u = current_user()
    node_list = Node.query.all()
    topic_list = Topic.query.all()
    for topic in topic_list:
        topic.comments_num = topic.comments_num()
        topic.last_comment_user = topic.last_comment_user()
    return render_template('home.html', node_list=node_list, topic_list=topic_list, u=u,)

routes/node.py
from models.node import Node
from models.topic import Topic
from routes import *
from functools import wraps

main = Blueprint('node', __name__)

Model = Node


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        u = current_user()
        if u.id != 1:
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/')
@admin_required
def index():
    ms = Model.query.all()
    return render_template('node_index.html', node_list=ms)


@main.route('/add', methods=['POST'])
@admin_required
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.index'))


@main.route('/<int:id>')
def show(id):
    ms = Model.query.all()
    m = Model.query.get(id)
    u = current_user()
    topic_list = m.topics
    for topic in topic_list:
        topic.comments_num = topic.comments_num()
        topic.last_comment_user = topic.last_comment_user()
    return render_template('node.html', node=m, node_list=ms, u=u)


@main.route('/delete/<int:id>')
@admin_required
def delete(id):
    m = Model.query.get(id)
    m.delete()
    return redirect(url_for('.index'))

routes/timeline.py
from models.timeline import Timeline
from routes import *

# for decorators
from functools import wraps


main = Blueprint('timeline', __name__)

Model = Timeline


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        u = current_user()
        if u.id != 1:
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/')
def index():
    u = current_user()
    ms = u.timelines
    return render_template('timeline_index.html', timeline_list=ms, u=u)


@main.route('/new')
def new():
    return render_template('timeline_new.html')


@main.route('/edit/<id>')
def edit(id):
    m = Model.query.get(id)
    return render_template('timeline_edit.html', timeline=m)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    m = Model.query.get(id)
    m.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
def delete(id):
    m = Model.query.get(id)
    m.delete()
    return redirect(url_for('.index'))

routes/topic.py
from models.topic import Topic
from routes import *


main = Blueprint('topic', __name__)

Model = Topic


@main.route('/')
def index():
    ms = Model.query.all()
    return render_template('topic_index.html', topic_list=ms)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    node_id = m.node_id
    return redirect(url_for('node.show', id=node_id))


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    m.comments_num = m.comments_num()
    m.last_comment = m.last_comment()
    return render_template('topic.html', topic=m, u=u)


@main.route('/delete/<int:id>')
def delete(id):
    m = Model.query.get(id)
    m.delete()
    return redirect(url_for('.index'))


@main.route('/new/<int:id>')
def new(id):
    u = current_user()
    if u is not None:
        return render_template('topic_new.html', node_id=id, u=u)
    return render_template('register_or_login.html')

routes/user.py
from models.user import User
from routes import *


main = Blueprint('user', __name__)

Model = User


@main.route('/')
def login_view():
    ms = Model.query.all()
    return render_template('login_view.html', node_list=ms)


@main.route('/register')
def register():
    return render_template('user_register.html')


@main.route('/login')
def login():
    return render_template('user_login.html')


@main.route('/signup', methods=['POST'])
def signup():
    form = request.form
    m = Model(form)
    if m.valid():
        m.save()
        return redirect(url_for('.login'))
    return abort(404)


@main.route('/signin', methods=['POST'])
def signin():
    form = request.form
    m = Model(form)
    user = User.query.filter_by(username=m.username).first()
    if m.valid_login(user):
        session['user_id'] = user.id
        return redirect(url_for('home.home'))
    return redirect(url_for('user.login'))


@main.route('/profile/<int:id>')
def profile(id):
    u = current_user()
    u1 = User.query.get(id)
    topic_list = u1.topics
    for topic in topic_list:
        topic.comments_num = topic.comments_num()
        topic.last_comment_user = topic.last_comment_user()
    return render_template('user_profile.html', u=u, u1=u1, topic_list=topic_list)


@main.route('/setting')
def setting():
    u = current_user()
    return render_template('user_setting.html', u=u)


@main.route('/update', methods=['POST'])
def update():
    user = current_user()
    form = request.form
    u = User(form)
    if u.valid():
        user.update(u)
    return redirect(url_for('home.home'))


@main.route('/signout')
def signout():
    session.pop('user_id')
    return redirect(url_for('home.home'))


@main.route('/setting/avatar')
def setting_avatar():
    u = current_user()
    return render_template('user_setting_avatar.html', u=u)


@main.route('/upload', methods=['POST'])
def upload_file():
    u = current_user()
    uploads_dir = 'static/img/'
    f = request.files.get('uploaded')
    if f:
        filename = f.filename
        import uuid
        filename = str(uuid.uuid4()) + '.' + filename.split('.')[-1]
        path = uploads_dir + filename
        f.save(path)
        u.upload_avatar(path)
    return redirect(url_for('user.setting_avatar'))


@main.route('/setting/password', methods=['POST'])
def setting_password():
    u = current_user()
    form = request.form
    u.change_password(form)
    return redirect(url_for('user.setting'))


@main.route('/setting/base_info', methods=['POST'])
def setting_base_info():
    u = current_user()
    form = request.form
    u.change_base_info(form)
    return redirect(url_for('user.setting'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="/static/css/base.css">
    {% endblock %}
</head>
<body>

    <div class="bbs-top">
        <div class="bbs-logo">
            <a href="{{ url_for('home.home') }}">
                <img src="/static/img/adv.jpg">
            </a>
        </div>
        {% if u %}
        <div class="bbs-menu">
            <a href="{{ url_for('home.home') }}">首页</a>
            <a href="{{ url_for('user.profile', id=u.id) }}">{{ u.username }}</a>
            <a href="{{ url_for('timeline.index') }}">时间轴</a>
            <a href="{{ url_for('user.setting') }}">设置</a>
            <a href="{{ url_for('user.signout') }}">退出登录</a>
        </div>
        {% else %}
        <div class="bbs-menu">
            <a href="{{ url_for('home.home') }}">首页</a>
            <a href="{{ url_for('user.login') }}">登录</a>
            <a href="{{ url_for('user.register') }}">注册</a>
        </div>
        {% endif %}
    </div>

    <div class="bbs-main">
        {% block content %}
        {% endblock %}

        <div class="bbs-sidebar">
            <div class="bbs-sidebar-user">
                {% if u %}
                <div class="bbs-sidebar-user-username">
                    <img src="{{ u.avatar }}">
                    <a href="{{ url_for('user.profile', id=u.id) }}">{{ u.username }}</a>
                </div>
                <div class="bbs-sidebar-user-topics">
                        <a href="#"><span>0</span><br>节点收藏</a>
                        <a class="bbs-sidebar-user-topics-middle" href="#"><span>0</span><br>主题收藏</a>
                        <a href="#"><span>0</span><br>特别关注</a>
                </div>
                <div class="bbs-sidebar-user-new">
                    <a href="#">创作新的主题</a>
                </div>
                <div class="bbs-sidebar-user-message">
                    <a href="#">0条未读消息</a>
                </div>
                <div class="bbs-sidebar-user-gold">
                    <a href="#">›  在你开始发帖之前，请先领取初始资本</a>
                </div>
                {% else %}
                <div class="bbs-sidebar-text">
                    <span class="text-span-a">
                        V2EX = way to explore
                    </span>
                    <br>
                    <span class="text-span-b">
                        V2EX 是一个关于分享和探索的地方
                    </span>
                </div>
                <div class="bbs-sidebar-register">
                    <form action="{{ url_for('user.register') }}">
                        <button>现在注册</button>
                    </form>
                </div>
                <div class="bbs-sidebar-login">
                    <span>已注册用户请</span>
                    <a href="{{ url_for('user.login') }}">登录</a>
                </div>
                {% endif %}
            </div>
            <div class="bbs-sidebar-ad">
                <div class="bbs-sidebar-ad-img">
                    <a href="#"><img src="/static/img/adv.jpg"></a>
                </div>
                <div class="bbs-sidebar-ad-text">
                    <a href="#">广告</a>
                </div>
            </div>

        {% block topic %}
        {% endblock %}
        </div>
    </div>

    <div class="bbs-footer">
        <div class="bbs-footer-top">
            <a href="#">FAQ</a>
            <a href="#">API</a>
            <a href="#">我们的愿景</a>
            <a href="#">IP查询</a>
            <a href="#">广告投放</a>
            <a href="#">鸣谢</a>
            <a href="#">上网首页</a>
            <a href="#">1818人在线</a>
        </div>
        <div class="bbs-footer-middle">
            <div>
                创意工作者的社区
            </div>
            <div>
                World is powered by solitude
            </div>
        </div>
        <div class="bbs-footer-bottom">
            <img src="/static/img/dongtu.gif">
        </div>
    </div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/home.css">
{% endblock %}

{% block content %}
    <div class="bbs-content">
        <div class="bbs-content-nodes">
            <a href=" {{ url_for('home.home') }}">All</a>
            {% for node in node_list %}
            <a href="{{ url_for('node.show', id=node.id) }}">{{ node.name }}</a>
            {% endfor %}
        </div>
        <div class="bbs-content-add-topic">
            <a href="#"></a>
        </div>
        {% for topic in topic_list %}
        <div class="bbs-content-topic">
            <div class="bbs-content-topic-left">
                <a href="{{ url_for('user.profile', id=topic.user_id) }}"><img src="{{ topic.user.avatar }}"></a>
            </div>
            <div class="bbs-content-topic-middle">
                <div class="bbs-content-topic-middle-top">
                    <a href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.title }}</a>
                </div>
                <div class="bbs-content-topic-middle-bottom">
                    <a class="node" href="{{ url_for('node.show', id=topic.node_id) }}">{{ topic.node.name }}</a>
                    <span>•</span>
                    <a class="user" href="{{ url_for('user.profile', id=topic.user_id) }}">{{ topic.user.username }}</a>
                    {% if topic.last_comment_user %}
                    <span>•</span>
                    <comment>最后回复来自</comment>
                    <span>•</span>
                    <a class="user" href="{{ url_for('user.profile', id=topic.last_comment_user.id) }}">{{ topic.last_comment_user.username }}</a>
                    {% else %}
                    {% endif %}
                </div>
            </div>
            {% if topic.comments_num %}
            <div class="bbs-content-topic-right">
                <a href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.comments_num }}</a>
            </div>
            {% else %}
            {% endif %}
        </div>
        {% endfor %}
    </div>
{% endblock %}


{% block topic %}
    <div class="bbs-sidebar-topic">
        <div class="bbs-sidebar-topic-text">
            <span>今日热议主题</span>
        </div>
        {% for topic in topic_list %}
        <div class="bbs-sidebar-topic-cell">
            <a class="topic-avatar" href="{{ url_for('user.profile', id=topic.user_id) }}"><img src="{{ topic.user.avatar }}"></a>
            <a class="topic-title" href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.title }}</a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/node.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>node</title>
    <link rel="stylesheet" href="/static/css/node.css">
</head>
<body>
    <div class="bbs-top">
        <div class="bbs-logo">
            <a href="{{ url_for('home.home') }}">
                <img src="/static/img/adv.jpg">
            </a>
        </div>
        {% if u %}
        <div class="bbs-menu">
            <a href="{{ url_for('home.home') }}">首页</a>
            <a href="{{ url_for('user.profile', id=u.id) }}">{{ u.username }}</a>
            <a href="{{ url_for('timeline.index') }}">时间轴</a>
            <a href="{{ url_for('user.setting') }}">设置</a>
            <a href="{{ url_for('user.signout') }}">退出登录</a>
        </div>
        {% else %}
        <div class="bbs-menu">
            <a href="{{ url_for('home.home') }}">首页</a>
            <a href="{{ url_for('user.login') }}">登录</a>
            <a href="{{ url_for('user.register') }}">注册</a>
        </div>
        {% endif %}
    </div>

    <div class="bbs-main">
        <div class="bbs-content">
            <div class="bbs-content-nodes">
                <a href=" {{ url_for('home.home') }}">All</a>
                {% for node in node_list %}
                <a href="{{ url_for('node.show', id=node.id) }}">{{ node.name }}</a>
                {% endfor %}
            </div>
            <div class="bbs-content-add-topic">
                <a href="{{ url_for('topic.new', id=node.id) }}">发布新帖子</a>
            </div>

            {% for topic in node.topics %}
            <div class="bbs-content-topic">
                <div class="bbs-content-topic-left">
                    <a href="{{ url_for('user.profile', id=topic.user_id) }}"><img src="{{ topic.user.avatar }}"></a>
                </div>
                <div class="bbs-content-topic-middle">
                    <div class="bbs-content-topic-middle-top">
                        <a href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.title }}</a>
                    </div>
                    <div class="bbs-content-topic-middle-bottom">
                        <a class="node" href="{{ url_for('node.show', id=topic.node_id) }}">{{ topic.node.name }}</a>
                        <span>•</span>
                        <a class="user" href="{{ url_for('user.profile', id=topic.user_id) }}">{{ topic.user.username }}</a>
                        {% if topic.last_comment_user %}
                        <span>•</span>
                        <comment>最后回复来自</comment>
                        <span>•</span>
                        <a class="user" href="{{ url_for('user.profile', id=topic.last_comment_user.id) }}">{{ topic.last_comment_user.username }}</a>
                        {% else %}
                        {% endif %}
                    </div>
                </div>
                {% if topic.comments_num %}
                <div class="bbs-content-topic-right">
                    <a href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.comments_num }}</a>
                </div>
                {% else %}
                {% endif %}
            </div>
            {% endfor %}
        </div>

        <div class="bbs-sidebar">
            <div class="bbs-sidebar-user">
                {% if u %}
                <div class="bbs-sidebar-user-username">
                    <img src="{{ u.avatar }}">
                    <a href="{{ url_for('user.profile', id=u.id) }}">{{ u.username }}</a>
                </div>
                <div class="bbs-sidebar-user-topics">
                        <a href="#"><span>0</span><br>节点收藏</a>
                        <a class="bbs-sidebar-user-topics-middle" href="#"><span>0</span><br>主题收藏</a>
                        <a href="#"><span>0</span><br>特别关注</a>
                </div>
                <div class="bbs-sidebar-user-new">
                    <a href="#">创作新的主题</a>
                </div>
                <div class="bbs-sidebar-user-message">
                    <a href="#">0条未读消息</a>
                </div>
                <div class="bbs-sidebar-user-gold">
                    <a href="#">›  在你开始发帖之前，请先领取初始资本</a>
                </div>
                {% else %}
                <div class="bbs-sidebar-text">
                    <span class="text-span-a">
                        V2EX = way to explore
                    </span>
                    <br>
                    <span class="text-span-b">
                        V2EX 是一个关于分享和探索的地方
                    </span>
                </div>
                <div class="bbs-sidebar-register">
                    <form action="{{ url_for('user.register') }}">
                        <button>现在注册</button>
                    </form>
                </div>
                <div class="bbs-sidebar-login">
                    <span>已注册用户请</span>
                    <a href="{{ url_for('user.login') }}">登录</a>
                </div>
                {% endif %}
            </div>
            <div class="bbs-sidebar-ad">
                <div class="bbs-sidebar-ad-img">
                    <a href="#"><img src="/static/img/adv.jpg"></a>
                </div>
                <div class="bbs-sidebar-ad-text">
                    <a href="#">广告</a>
                </div>
            </div>
            <div class="bbs-sidebar-topic">
                <div class="bbs-sidebar-topic-text">
                    <span>今日热议主题</span>
                </div>
                {% for topic in node.topics %}
                <div class="bbs-sidebar-topic-cell">
                    <a class="topic-avatar" href="{{ url_for('user.profile', id=topic.user_id) }}"><img src="{{ topic.user.avatar }}"></a>
                    <a class="topic-title" href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.title }}</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="bbs-footer">
        <div class="bbs-footer-top">
            <a href="#">FAQ</a>
            <a href="#">API</a>
            <a href="#">我们的愿景</a>
            <a href="#">IP查询</a>
            <a href="#">广告投放</a>
            <a href="#">鸣谢</a>
            <a href="#">上网首页</a>
            <a href="#">1818人在线</a>
        </div>
        <div class="bbs-footer-middle">
            <div>
                创意工作者的社区
            </div>
            <div>
                World is powered by solitude
            </div>
        </div>
        <div class="bbs-footer-bottom">
            <img src="/static/img/dongtu.gif">
        </div>
    </div>



</body>
</html>

templates/timeline_index.html
{% extends 'base.html' %}

{% block title %}timeline{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/timeline.css">
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="/static/js/timeline.js"></script>
{% endblock %}

{% block content %}
    <div class="bbs-content">
        <div class="timeline-add">
            <span>
                你在想什么？
            </span>
            <!--<form action="{{ url_for('timeline.add') }}" method="post">-->
                <input class="user-id" type="hidden" name="user_id" value="{{ u.id }}">
                <textarea class="timeline-content" contextmenu="" name="content"  style="resize:none"></textarea>
                <div class="timeline-add-public">
                    <button class="timeline-add-button">发布</button>
                </div>
            <!--</form>-->
        </div>

        <div class="timelines">
            {% for timeline in timeline_list %}
            <div class="timeline-cell">
                <div class="timeline-avatar">
                    <a><img src="{{ u.avatar }}"></a>
                </div>
                <div class="timeline-username-content">
                    <a href="{{ url_for('user.profile', id=u.id) }}">{{ u.username }}</a>
                    <time>{{ timeline.created_time }}</time>
                    <br>
                    <span class="span-timeline">{{ timeline.content }}</span>
                </div>
                <div class="timeline-operation">
                    <a class="timeline-delete" data-id="{{ timeline.id }}">删除</a>
                    <a class="timeline-edit" data-id="{{ timeline.id }}">编辑</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/topic.html
{% extends 'base.html' %}

{% block title %}
    topic
{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/topic.css">
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="/static/js/api.js"></script>
    <script src="/static/js/comment.js"></script>
{% endblock %}

{% block content %}
    <div class="bbs-content">
        <div class="bbs-content-top">
            <div class="bbs-content-top-left">
                <div class="bbs-content-top-nodes">
                <a href=" {{ url_for('home.home') }}">All</a>
                         ›
                <a href="{{ url_for('node.show', id=topic.node.id) }}">{{ topic.node.name }}</a>
                         ›
                <a href="{{ url_for('topic.show', id=topic.id) }}">{{ topic.title }}</a>
                </div>
                <div class="bbs-content-top-title">
                    <h2>{{ topic.title }}</h2>
                </div>
                <div class="bbs-content-top-author">
                    <a href="{{ url_for('user.profile', id=topic.user_id) }}">{{ topic.user.username }}</a>
                    <span> • 发布于{{ topic.created_time }}</span>
                </div>
            </div>

            <div class="bbs-content-top-avatar">
                <a href="#"><img src="{{ topic.user.avatar }}"></a>
            </div>

            <div class="bbs-content-top-content">
                <p>{{ topic.content }}</p>
            </div>
        </div>


        <div class="bbs-content-middle">
            {% if topic.last_comment %}
            <div class="bbs-content-middle-top">
                {{ topic.comments_num }} 回复 | 直到 {{ topic.last_comment.created_time }}
            </div>
            {% else %}
            <div class="bbs-content-middle-top">
                0 回复
            </div>
            {% endif %}
            <div class="comment-container">
                {% for comment in topic.comments %}
                <div class="bbs-content-middle-cell">
                    <div class="bbs-content-middle-cell-avatar">
                        <a><img src="{{ comment.user.avatar }}"</a>
                    </div>
                    <div class="bbs-content-middle-cell-comments">
                        <div class="bbs-content-middle-cell-username">
                            <a href="{{ url_for('user.profile', id=comment.user_id) }}">{{ comment.user.username }}</a>
                            <span>{{ comment.created_time }}</span>
                        </div>
                        <div class="bbs-content-middle-cell-content">
                            {{ comment.content }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>

        <div class="bbs-content-bottom">
            <div class="bbs-content-bottom-new">
                <span>添加一条新的回复</span>
            </div>
            <div class="bbs-content-bottom-add">
                <!--<form action="{{ url_for('comment.add') }}" method="post">-->
                    <input class="user-id" type="hidden" name="user_id" value="{{ u.id }}">
                    <input class="topic-id" type="hidden" name="topic_id" value="{{ topic.id }}">
                    <textarea class="comment-content" name="content"  style="resize:none"></textarea>
                    <button class="comment-add">回复</button>
                    <span>请尽量让自己的回复能够对别人有帮助回复</span>
                <!--</form>-->
            </div>
            <div class="bbs-content-bottom-index">
                <a href="{{ url_for('home.home') }}">←V2EX</a>
            </div>
        </div>

    </div>





{% endblock %}


</body>
</html>

templates/user_setting.html
{% extends 'base.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/setting.css">
{% endblock %}


{% block content %}
    <div class="bbs-content">
        <div class="user-info-base">
            <div class="user-nodes">
                <a href="{{ url_for('home.home') }}">V2EX</a>
                ›
                <span>设置</span>
            </div>
            <div class="user-update">
                <form action="{{ url_for('user.setting_base_info') }}" method="post">
                    <span>用户名</span>
                    <a>{{ u.username }}</a>
                    <br>
                    <span>电子邮件</span>
                    <input type="text" name="email" value="{{ u.email }}">
                    <br>
                    <span>个人网站</span>
                    <input type="text" name="website" value="{{ u.website }}">
                    <br>
                    <span>所在公司</span>
                    <input type="text" name="company" value="{{ u.company }}">
                    <input type="hidden" name="username" value="{{ u.username }}">
                    <br>
                    <button>保存设置</button>
                </form>
            </div>

        </div>

        <div class="user-info-avatar">
            <div class="user-info-text">
                头像上传
            </div>
            <div class="user-info-avatar-avatar">
                <form action="{{ url_for('user.setting_avatar') }}" method="get">
                    <span>当前头像</span>
                    <img class="img1" src="{{ u.avatar }}">
                    <img class="img2" src="{{ u.avatar }}">
                    <img class="img3" src="{{ u.avatar }}">
                    <br>
                    <button>上传新头像</button>
                </form>

            </div>
            <div class="user-info-avatar-regulation">
                <span>关于图像的规则</span>
                <li>V2EX 禁止使用任何低俗或者敏感图片作为头像</li>
                <li>如果你是男的，请不要用女人的照片作为头像，这样可能会对其他会员产生误导</li>
            </div>
        </div>

        <div class="user-info-password">
            <form action="{{ url_for('user.setting_password') }}" method="post">
                <span>当前密码</span>
                <input type="password" name="old_password">
                <br>
                <span>新密码</span>
                <input type="password" name="new_password">
                <br>
                <span>再次输入新密码</span>
                <input type="password" name="commit_password">
                <br>
                <button>更改密码</button>
            </form>
        </div>
    </div>
{% endblock %}